version: '3.7'

volumes:
    postgres_data: 
        driver: local

networks:
  external: 
    name: ehr-network

services:

  users_container:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/UsersService && npm run test"
    volumes:
        - ./UsersService:/app/UsersService
        - ./entities-lib:/app/entities-lib
        - ./config-lib:/app/config-lib
        - ./error/:/root/.npm/_logs/
    depends_on:
      - mariadb
    environment: 
    # Timezone. Variable from .env file
      - TZ
    tty: true
    stdin_open: true
    container_name: ${USERS_CONTAINER_NAME}
    networks: 
      - external

  # MariaDB
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    networks: 
      - external
    restart: on-failure