version: '3.7'

volumes:
    postgres_data: 
        driver: local

networks:
  external1: 
    name: front-back-network
  external2:
    name: back-mariadb-network

services:

  # NestJS-Graphql backend
  users:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/UsersService && bash install.sh"
    volumes:
        - ./UsersService:/app/UsersService
        - ./entities-lib:/app/entities-lib
        - ./config-lib:/app/config-lib
        - ./certs:/app/certs
        - ./error/:/root/.npm/_logs/
    depends_on:
      - mariadb
    environment: 
    # Timezone. Variable from .env file
      - TZ
      - MAILER_CONTAINER_NAME
      - MAILER_CONTAINER_PORT
      - USERS_CONTAINER_PORT
      - JWT_KEY
    tty: true
    stdin_open: true
    container_name: ${USERS_CONTAINER_NAME}
    networks: 
      - external1
      - external2

  products:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/ProductsService && bash install.sh"
    volumes:
        - ./ProductsService:/app/ProductsService
        - ./entities-lib:/app/entities-lib
        - ./config-lib:/app/config-lib
        - ./certs:/app/certs
        - ./error/:/root/.npm/_logs/
    depends_on:
      - mariadb
    environment: 
    # Timezone. Variable from .env file
      - TZ
      - MAILER_CONTAINER_NAME
      - MAILER_CONTAINER_PORT
      - USERS_CONTAINER_NAME
      - USERS_CONTAINER_PORT
      - PRODUCTS_CONTAINER_PORT
      - JWT_KEY
    tty: true
    stdin_open: true
    container_name: ${PRODUCTS_CONTAINER_NAME}
    networks: 
      - external1
      - external2
  
  mailer:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/MailerService && bash install.sh"
    volumes:
        - ./MailerService:/app/MailerService
        - ./certs:/app/certs
        - ./error/:/root/.npm/_logs/
    environment: 
    # Timezone. Variable from .env file
      - TZ
      - MAILER_CONTAINER_PORT
    tty: true
    stdin_open: true
    container_name: ${MAILER_CONTAINER_NAME}
    networks: 
      - external1
      - external2

  # React NextJS Frontend Container
  front:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/FrontService && bash install.test.sh"
    ports:
      - "${FRONTEND_CONTAINER_PORT}:443"
    volumes:
      - ./FrontService:/app/FrontService
      - ./certs:/app/certs
    environment: 
    # Timezone. Variable from .env file
      - TZ
      - USERS_CONTAINER_NAME
      - USERS_CONTAINER_PORT
      - PRODUCTS_CONTAINER_NAME
      - PRODUCTS_CONTAINER_PORT
    tty: true
    stdin_open: true
    container_name: ${FRONTEND_CONTAINER_NAME}
    depends_on:
      - ${PRODUCTS_CONTAINER_NAME}
      - ${USERS_CONTAINER_NAME}
      - ${MAILER_CONTAINER_NAME}
    networks: 
      - external1

  # MariaDB
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    networks: 
      - external2
    restart: on-failure

  cypress_container:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/TFG-Test && npm install && bash wait-to-front.sh && npm run test"
    volumes:
      - ./TFG-Test:/app/TFG-Test
    tty: true
    stdin_open: true
    depends_on:
      - ${FRONTEND_CONTAINER_NAME}
    networks: 
      - external1