version: '3.7'

volumes:
    postgres_data: 
        driver: local

networks:
  external: 
    name: ehr-network

services:

  # NestJS-Graphql backend
  backend_container:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/TFG-Backend && bash install.sh"
    volumes:
        - ./TFG-Backend:/app/TFG-Backend
        - ./error/:/root/.npm/_logs/
    depends_on:
      - mariadb
    environment: 
    # Timezone. Variable from .env file
      - TZ
    tty: true
    stdin_open: true
    container_name: ${BACKEND_CONTAINER_NAME}
    networks: 
      - external

  # React NextJS Frontend Container
  frontend_container:
    image: arturoalcaniz/node-image
    command: bash -c "cd /app/TFG-Frontend && bash install.sh"
    ports:
      - "${FRONTEND_CONTAINER_PORT}:3000"
    volumes:
      - ./TFG-Frontend:/app/TFG-Frontend
    environment: 
    # Timezone. Variable from .env file
      - TZ
    tty: true
    stdin_open: true
    container_name: ${FRONTEND_CONTAINER_NAME}
    networks: 
      - external

  # MariaDB
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USERNAME}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    networks: 
      - external
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: on-failure

  # Adminer
  adminer:
    image: adminer:latest
    container_name: ${ADMINER_CONTAINER_NAME}
    environment: 
      - ADMINER_DEFAULT_SERVER=${MARIADB_CONTAINER_NAME}
      - ADMINER_DESIGN=galkaev
      - TZ
    ports: 
      - 8080:8080
    networks:
      - external
