apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: operation
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
      - name: database
        image: arturoalcaniz/mariadb
        ports:
         - containerPort: 3306
        volumeMounts:
        - name: my-do-volume
          mountPath: "/var/lib/mysql"
      imagePullSecrets:
       - name: dockercred
      initContainers:
      - name: mariadb-data
        image: busybox
        command: ["/bin/chmod","-R","777", "/data"]
        volumeMounts:
        - name: my-do-volume
          mountPath: /data
      volumes:
        - name: my-do-volume
          persistentVolumeClaim:
            claimName: csi-pvc

---
apiVersion: v1
kind: Service
metadata: 
  name: database
  namespace: operation
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    role: db
