apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: operation
  labels:
    back: front

spec:
  replicas: 1
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      containers:
      - name: front
        image: arturoalcaniz/front-service:latest
        imagePullPolicy: "Always"
        ports:
         - containerPort: 443
        command: ["bash", "-c"]
        args: ["cd /app/FrontService && bash install.sh"]
      imagePullSecrets:
       - name: dockercred

---
apiVersion: v1
kind: Service
metadata: 
  name: front
  namespace: operation
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    role: front
