apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: operation
  labels:
    back: front

spec:
  replicas: 1
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      priorityClassName: high-priority
      containers:
      - name: front
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_KEY
        - name: PRODUCTS_CONTAINER_PORT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PRODUCTS_CONTAINER_PORT
        - name: PRODUCTS_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PRODUCTS_CONTAINER_NAME
        - name: USERS_CONTAINER_PORT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USERS_CONTAINER_PORT
        - name: USERS_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USERS_CONTAINER_NAME
        - name: MAILER_CONTAINER_PORT
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MAILER_CONTAINER_PORT
        - name: MAILER_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MAILER_CONTAINER_NAME
        - name: FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_APP_ID
        - name: FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_MESSAGING_SENDER_ID
        - name: FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_STORAGE_BUCKET
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_PROJECT_ID
        - name: FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_AUTH_DOMAIN
        - name: FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: FIREBASE_API_KEY
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DOMAIN
        image: arturoalcaniz/front-service:latest
        imagePullPolicy: "Always"
        ports:
         - containerPort: 443
        command: ["bash", "-c"]
        args: ["cd /app/FrontService && bash install.sh"]
      imagePullSecrets:
       - name: dockercred