apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: operation
spec:
  replicas: 1
  selector:
    matchLabels:
      role: CICD
  template:
    metadata:
      labels:
        role: CICD
    spec:
      priorityClassName: low-priority
      containers:
      - name: jenkins
        image: arturoalcaniz/jenkins-service
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
         - containerPort: 8080
        volumeMounts:
        - name: volume-jenkins
          mountPath: "/var/lib/jenkins"
        command: ["bash", "-c"]
        args: ["cd /app/JenkinsService && bash install.sh"]
      imagePullSecrets:
       - name: dockercred
      initContainers:
      - name: jenkins-data
        image: busybox
        command: ["/bin/chmod","-R","777", "/jenkins-data"]
        volumeMounts:
        - name: volume-jenkins
          mountPath: /jenkins-data
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: false
        - name: docker-directory
          mountPath: "/var/lib/docker"
          readOnly: false
      volumes:
        - name: volume-jenkins
          persistentVolumeClaim:
            claimName: volume-jenkins
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
            type: File
        - name: docker-directory
          hostPath:
            path: "/var/lib/docker"