apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 100000
globalDefault: false
description: "En esta prioridad estan los pods que no son necesarios para la ejecución de la aplicacion"