kind: PersistentVolume
apiVersion: v1
metadata:
  name: csi-pvc
  namespace: operation
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-pvc
  namespace: operation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi