kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-jenkins
  namespace: operation
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins-data"
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume-jenkins
  namespace: operation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi