kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-products
  namespace: operation
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume-products
  namespace: operation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi